---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_webserver: false
    php_default_version_debian: "7.2"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.memcached
    - role: geerlingguy.php
    - role: geerlingguy.php-memcached

  post_tasks:
    - name: Run test script to confirm Memcached is reachable via PHP.
      script: memcached-test.php
      args:
        executable: php
      changed_when: false
